In [ ]:
a = 10
b = 20

print(a+b)

30


In [ ]:
a = 2
b = 67

print (a+b)

69


In [ ]:
num = 25
print(num)
print(type(num))

25
<class 'int'>


In [ ]:
num_2 = 20.5
print(type(num_2))

<class 'float'>


In [ ]:
num_1 = 2.5e12
print(num_1)
print(type(num_1))

2500000000000.0
<class 'float'>


In [ ]:
x = 7
a = float(x)

print (x , type(x))
print (a , type(a))

7 <class 'int'>
7.0 <class 'float'>


In [ ]:
y = 20.8
b = int(y)

print ( y ,type(y))
print ( b , type(b))

20.8 <class 'float'>
20 <class 'int'>


In [ ]:
my_list = [10 , "kavindu" , 5.7 , True , 40]

print(my_list)
print(type(my_list))
print(my_list[2])
print(my_list[-1])
print(my_list[1:4])
print(my_list[:4])
print(my_list[2:])

my_list[1] = "gamage"

print(my_list)

[10, 'kavindu', 5.7, True, 40]
<class 'list'>
5.7
40
['kavindu', 5.7, True]
[10, 'kavindu', 5.7, True]
[5.7, True, 40]
[10, 'gamage', 5.7, True, 40]


In [ ]:
my_list_2 = [50 , "tharaka" , 1.2 , False , 50]

print(my_list_2)


[50, 'tharaka', 1.2, False, 50]


In [ ]:
my_list_3 = [10 , 5 , "tharaka" , 1.2 , False , 50]

my_list_3[2:5] = ["gamage" , 4.2 , True]
print(my_list_3)

my_list_3.append("dog")
print(my_list_3)

my_list_3.insert(2 , "nimal")
print(my_list_3)

my_list_3.remove ("nimal")
print(my_list_3)


[10, 5, 'gamage', 4.2, True, 50]
[10, 5, 'gamage', 4.2, True, 50, 'dog']
[10, 5, 'nimal', 'gamage', 4.2, True, 50, 'dog']
[10, 5, 'gamage', 4.2, True, 50, 'dog']


In [ ]:
my_list_4 = [1,2,3,4,5]
my_list_5 = [10,11,12,13]

my_list_4.extend (my_list_5)
print(my_list_4)

my_list_4.remove (1)
print(my_list_4)

my_list_4.pop (1)
print(my_list_4)

print(len(my_list_4))

del my_list_4[3]
print(my_list_4)




[1, 2, 3, 4, 5, 10, 11, 12, 13]
[2, 3, 4, 5, 10, 11, 12, 13]
[2, 4, 5, 10, 11, 12, 13]
7
[2, 4, 5, 11, 12, 13]


In [ ]:
students = ["Amal" , "Binu" , "Chamara"]

students.append("Dilum")
print(students)

students.insert(2,"Ishan")
print(students)

students.remove("Amal")
print(students)

students.insert(0, "farha")
print(students)


['Amal', 'Binu', 'Chamara', 'Dilum']
['Amal', 'Binu', 'Ishan', 'Chamara', 'Dilum']
['Binu', 'Ishan', 'Chamara', 'Dilum']
['farha', 'Binu', 'Ishan', 'Chamara', 'Dilum']


In [ ]:
my_list_6 = [1,2,3,4,5,6,7,8]

my_list_6.clear()
print(my_list_6)

[]


In [ ]:
my_list_7 = ["banana" , "apple" , "mango" , "cat" , "bird"]
my_list_7.sort()
print(my_list_7)

my_list_7 = ["banana" , "apple" , "mango" , "cat" , "bird" , "Dog"]
my_list_7.sort()
print(my_list_7)

['apple', 'banana', 'bird', 'cat', 'mango']
['Dog', 'apple', 'banana', 'bird', 'cat', 'mango']


In [ ]:
num_list = [10,8,5,31,15,7,80,58]
num_list.sort(reverse=True)
print(num_list)

[80, 58, 31, 15, 10, 8, 7, 5]


In [ ]:
my_list_8 = [0,5,7,11,6,9]

my_list_9 = my_list_8.copy()

print(my_list_8)
print(my_list_9)

my_list_8 [1] = 15 

print(my_list_8)
print(my_list_9)

my_list_8.reverse()
print(my_list_8)

new_list = my_list_8 + my_list_9
print(new_list)

[0, 5, 7, 11, 6, 9]
[0, 5, 7, 11, 6, 9]
[0, 15, 7, 11, 6, 9]
[0, 5, 7, 11, 6, 9]
[9, 6, 11, 7, 15, 0]
[9, 6, 11, 7, 15, 0, 0, 5, 7, 11, 6, 9]


In [ ]:
sports = ("tennis" , "cricket" , "football")

print(sports)
print(type(sports))
print(len(sports))
print(sports[1])

('tennis', 'cricket', 'football')
<class 'tuple'>
3
cricket


In [ ]:
days = ("monday" ,)

print(days)
print(type(days))

('monday',)
<class 'tuple'>


In [ ]:
fruits = ("apple" , "banana" , "orange")

x = list(fruits)

print(type(x))

x[1] = "grates"

print(x)

fruits = tuple(x)
print(fruits , type(fruits))

<class 'list'>
['apple', 'grates', 'orange']
('apple', 'grates', 'orange') <class 'tuple'>


In [ ]:
nested_tuple = (1 , 2 , 3) , ("a" , "b" , "c") , (True , False)

print(nested_tuple[1][1])
print(nested_tuple[2][0])

b
True


In [ ]:
sports = {"tennis" , "cricket" , "football"}

print(sports)
print(type(sports))

sports.add("vollyball")

print(sports)


{'tennis', 'cricket', 'football'}
<class 'set'>
{'tennis', 'cricket', 'football', 'vollyball'}


In [ ]:
set_1 = {"tennis" , "cricket" , "football"}
set_2 = {"apple" , "banana"}

set_1.update(set_2)

print(set_1)


{'tennis', 'cricket', 'apple', 'football', 'banana'}


In [ ]:
set_1 = {"tennis" , "cricket" , "football"}

list_1 = ["a" , "b" , "c"]

set_1.update(list_1)

print(set_1)


{'tennis', 'cricket', 'c', 'a', 'b', 'football'}


In [ ]:
list_1 = [50,60,30,40,50,25,60,30,40]

set_1 = set(list_1)

print(set_1)

list_1 = list(set_1)

list_1.sort()

print(list_1)

{40, 50, 25, 60, 30}
[25, 30, 40, 50, 60]


In [ ]:
x = range(1,7,1)

y = range(1,12,2)

z = range(3,24,4)

print(x)
print(y)
print(type(x))

print(x[2])





range(1, 7)
range(1, 12, 2)
<class 'range'>
3


In [ ]:
this_dict = {
    "name" : "sugar",
    "weight" : "1Kg",
    "price" : 130.35
}

print(this_dict)
print(type(this_dict))

print(this_dict["weight"])

print(this_dict.get("weight"))

print(len(this_dict))

this_dict["price"] = 140.00
print(this_dict)

this_dict["color"] = "brown"
print(this_dict)

this_dict.update({"exp" : "jan 2026" , "price" : "200.50"})
print(this_dict)

this_dict.pop("price")
print(this_dict)

this_dict.popitem()
print(this_dict)

del this_dict["color"]
print(this_dict)

this_dict.clear()
print(this_dict)

{'name': 'sugar', 'weight': '1Kg', 'price': 130.35}
<class 'dict'>
1Kg
1Kg
3
{'name': 'sugar', 'weight': '1Kg', 'price': 140.0}
{'name': 'sugar', 'weight': '1Kg', 'price': 140.0, 'color': 'brown'}
{'name': 'sugar', 'weight': '1Kg', 'price': '200.50', 'color': 'brown', 'exp': 'jan 2026'}
{'name': 'sugar', 'weight': '1Kg', 'color': 'brown', 'exp': 'jan 2026'}
{'name': 'sugar', 'weight': '1Kg', 'color': 'brown'}
{'name': 'sugar', 'weight': '1Kg'}
{}


In [ ]:
this_dict = {
    "name" : "sugar",
    "weight" : "1Kg",
    "price" : 130.35
}

print(this_dict)

copy = this_dict.copy()
print(copy)

this_dict.update({"exp" : "jan 2026" , "price" : "200.50"})
print(this_dict)
print(copy)


{'name': 'sugar', 'weight': '1Kg', 'price': 130.35}
{'name': 'sugar', 'weight': '1Kg', 'price': 130.35}
{'name': 'sugar', 'weight': '1Kg', 'price': '200.50', 'exp': 'jan 2026'}
{'name': 'sugar', 'weight': '1Kg', 'price': 130.35}


In [ ]:
#assignment operators

x = 5 # assignment
x += 3 # add and assign
x -= 3 #subtract assign
x *= 3 # multiply amd assign
x /= 3 # devison amd assign

In [ ]:
#comparison operatorss
x,y = 5,8

print(x == y)
print(x < y)
print(x > y)
print(x <= y)
print(x >= y)
print(x != y)

False
True
False
True
False
True


In [ ]:
#logical operators

# And , Or , Not

In [ ]:
x , y = 5, 6

print(x is y)

x = 5
y = x

print(x is y)

x = 5
y = 5

print(x is y)


False
True
True


In [ ]:
x , y = 5, 10

x = x & y

print(x)

0


In [ ]:
n = 15

if n % 2 == 0:
    print("n is even")
else:
    print("n is odd")

n is odd


In [ ]:
list = [1,2,3,4,5,6,7]

# x = len(list)

# if x == 0:
#     print("empty list")
# else:
#     print("non empty list")

if list:
    print("non empty list")
else:
    print("empty list")

non empty list


In [ ]:
r = 7
P = 3.14

if r <= 0 :
    print("r is not valid")
else:
    circumference = 2 * P * r
    print(circumference)

43.96


In [ ]:
a = 3
b = 4

if a <= 0 or b <=0 :
    print(" give positive value ")
else:
    c = (a ** 2 + b ** 2) ** 0.5
    print(c)

5.0


In [ ]:
num_1 = 1
num_2 = 3
num_3 = 4

if num_1 > num_2 and num_1 > num_3 :
    print ("largest :",num_1)
elif num_2 > num_1 and num_2 > num_3 :
    print ("largest :",num_2)

else :
    print("largest :",num_3)



largest : 4


In [ ]:
#slide change the to about program to display number in dicending order

num_1 = 1
num_2 = 8
num_3 = 4

if num_1 > num_2 and num_1 > num_3 :
    if num_2 > num_3 :
        print("num_1,num_2,num_3")
    else:
        print("num_1,num_3,num_2")
elif num_2 > num_1 and num_2 > num_3 :
    if num_1 > num_3 :
        print("num_2,num_1,num_3")
    else:
        print("num_2,num_3,num_1")

else :
    if num_1 > num_2 :
        print("num_3,num_1,num_2")
    else:
        print("num_3,num_2,num_1")

num_2,num_3,num_1


In [ ]:
a = 11

r = "even" if a % 2 == 0 else "odd"

print(r)

odd


In [ ]:
#given any intiger n ,print the abslute value using a ternary operator (without using abs() function)

n = -28

r = n if n >= 0 else -n

print(r)

28


In [ ]:
v = 12

match v:
    case 10:
        print("value is 10")
    case 11:
        print("value is 11")
    case _:
        print("default value") 

default value


In [ ]:
#write a python program that take integer input from the user represent the week day numbers (1-7) and print the horresponding weekdays name using match case statement

num_1 = int(input("enter the number :"))

match num_1:
    case 1:
        print("moday")
    case 2:
        print("tuesday")
    case 3:
        print("wednesday")
    case 4:
        print("thursday")
    case 5:
        print("friday")
    case 6:
        print("saturday")
    case 7:
        print("sunday")
    case _:
        print("inavalid number enter number between 1 to 7")

In [ ]:
#write a python program that takes and input string representing a traffic light colors
#red , yellow , green or blinking
#use structurel patten matching to print the following 
# print stop if color is red or blinking
# print slow down if color is yellow
# print go if color is green
# print invalid color any other input

color = input("enter color")

match color:
    case "red" | "blinking":
        print("stop")
    case "yellow":
        print("slow down")
    case "green":
        print("go")
    case _:
        print("invalid color")

In [ ]:
numbers = [4,3]

match numbers:
    case (x,y):
        print(x*y)
    case (x,y,z):
        print(x*y*z)
    case _ :
        print("invalid")

12


In [ ]:
#write a python programe that read a list of tempresure readings :
#if the list has excatly two elments,print there averrage
#if the list has excatly four elements, clculate and print the diffrent between the sum of the frist two reading and sum the last two reading
#for any other list length , print unsupported number of reading

num = [7,8,3,6]

match num:
    case (x,y):
        print((x+y)/2)
    case(x,y,z,r):
        print((x+y) - (z+r))
    case _:
        print("unsupported number")

In [ ]:
my_list = [11,8,6,9,18]

for item in my_list:

    if item%2 == 0:
        print (item)

In [ ]:
#write a python programm to display squre value of firt ten intiger

num = range(1,11)

for item in num:
    print(item**2)

# ================

# for item in range(1,11):
#     print(item**2)


In [ ]:
#get a positive intiger as a user input. then display all squre numbers witch are bellow than the input number

num = int(input ("enter the number"))

for item in range(1,num):
    if item**2 < num:
        print(item**2)
    else:
        break


In [ ]:
#write a python code to demostrate the lenear search

list = [1,2,3,4,5,6,7,8,9,10]

found = False

num = int(input("enter the number"))

for item in list:
    if item == num:
        print("number found")
        found = True
if not found:
        print("number not found")

# ======================================

# list = [1,2,3,4,5,6,7,8,9,10]
# num = int(input("enter the number"))
# for item in list:
#     if item == num:
#         print("number found")
#         break
# else:
#       print("number not found")
    

In [ ]:
list = [10,0,30,40,50]

num = list[0]

for item in list:
    if item > num:
       num = item
print(num)

In [ ]:
my_list = [5,10,4,6,9,7,2]

result = [item ** 2 for item in my_list]

print(result)

In [ ]:
#create the list with the squers of even numbers between 1 to 10 (include) using list combination

result = [item ** 2 for item in range(1,11) if item % 2 == 0]

print(result)

In [ ]:
#write a python program using a while loop to display all positive integers which are bellow than the user input n (you check the input validity)

num = int(input("enter the number"))

if num <= 0:
    print("Enter positive number")

count = 1

while num != count:
        print(count)
        count += 1


#in both for loop and while loop if you need "continue" key word it will exit from the current iteration


In [ ]:
# write a python programme to reverse the digits of and given integer using a while loop

# ex : input = 9725
#      output = 5279

num = int(input("input number"))
rev = 0 

while num > 0:
    digits = num % 10
    rev = rev * 10 + digits
    num = num // 10

print(rev)

In [ ]:
def max_value(list):
    list =[2,4,5,6,7,8,9,20]
    max_value =list[0]
    for num in list:
        if num > max_value :
            max_value= num
            
    return max_value
print("maximum value of in the list:",max_value(list))

In [ ]:
def count(list):
    list =[2,4,5,6,7,8,9,20]
    count=0
    for num in list:
        if num % 2 == 0:
            count += 1
    return count
print( "even num count:",count(list))

In [ ]:
#write a function name "remove_duplicate(list)" that return a list with duplicate remove (reserving the original order)

def remove_duplicate(list):

    list = [1,5,6,5,3,1,4]
    new_list = []

    for item in list:
        if item not in new_list:
            new_list.append(item)

    return new_list
        
print(remove_duplicate(list))

In [ ]:
#write a function "factorial(n)" that returns the factorial of a given number n

def factorial(n):
    result = 1
    if n == 0:
        return result
    
    for item in range(1,n+1):
        result *= item

    return result

print(factorial(5))

In [ ]:
#default argument
def add_num(a,b=2):
    return a+b
    
print(add_num(9))

In [ ]:
#write a function that calculate and  returns the value of a number race to a sertain power. the function should accept two arguments : the number and exponent. if the exponent is nt provided it should calculate squre of the number

def number(num,exponent=2):
    return num ** exponent

print(number(2))
print(number(2,3))

In [ ]:
#keyword argument

def number(a,b):
    print(a)
    print(b)

number(b=2,a=5)
number(a=3,b=9)

In [ ]:

#write a function that calculate and employes next salary. the function should accept based sallry, bonus(default to 0), and tax rate(default to 10%). the next sallry is calculated by adding the bonus to the based sallry and subtraction the tax. demostarte difrent wayes of calling this function using possitional and keyword argument

def sallry(based_sallry,bonus,tax_rate):
    return (based_sallry+bonus) - (based_sallry+bonus) * tax_rate

print(sallry(based_sallry=30000, bonus=5000, tax_rate=0.1))

In [ ]:
#arbitrary position argument

def arbitarrary_position(*args):
    print(args)
    print(type(args))

    for arg in args:
        print(arg)

arbitarrary_position(1,2,3,4)

In [ ]:
#write a function multifly all that accepts any number of numbers and returns therir products. if no numbers are provided return 1

def multifly(*args):
    count = 1
    for arg in args:
        count *= arg
    return count

print(multifly(1,2,3,4))

In [ ]:
dict = {
    "name" : "Jone",
    "age" : 28,
    "city" : "colombo"
}

for key in dict.keys():
 print(key)

for value in dict.values():
 print(value)

for key,value in dict.items():
 print("key :",key,",value :",value)

In [ ]:
def arbitrary_keyword_args(**kwargs):
    print(kwargs)
    print(type(kwargs))

arbitrary_keyword_args(name="kavindu",age=28,city="galle")

In [ ]:
def arbitrary_keyword_args(**kwargs):
    print(kwargs)
    print(type(kwargs))

    for key,value in kwargs.items():
        print("key :",key,",value :",value)

arbitrary_keyword_args(name="kavindu",age=28,city="galle")

In [ ]:
#you are developing a student management system 
#   1.write a function add_student() with access any number of keyword argument where keys are student id's and values are student's name
#   2.the function should store all student into a dictonary 
#   3.write another function display_student which acccept the dictonary and prints all students id's and names in a need format
#   4.demostarte your function by adding at least 5 student using key word argument and disply them

#======================
def add_student(**kwargs):
    students = {}

    for s_id , s_name in kwargs.items():
        students[s_id] = s_name
        
    return students

#=====================
def display_student(students):
    for s_id , s_name in students.items():
        print("student_id :" , s_id,", student_name :", s_name)

#=====================
students = add_student(
    S001="Kavindu Tharaka",
    S002="Kavindu Tharaka",
    S003="Kavindu Tharaka",
    S004="Kavindu Tharaka",
    S005="Kavindu Tharaka"
)

#=====================
display_student(students)

In [ ]:
#python built in function (https://docs.python.org/3/library/functions.html#func-range)

#map(function,iterable)

def find_squre(x):
    return x**2

my_list = [1,2,3,4,5]

squre_value = map(find_squre,my_list)

print(squre_value)
print(list(squre_value))



[1, 4, 9, 16, 25]


In [ ]:
#your are given a list of tempresures in celsius 
#celsius_value = [0,20,37,100,-10]
#write a python function that convert dis list into fahrenheit using a formula "f = c*9%5 +32" 
#use the map function to perform the conversion 
#return the list of fehrenheit value

# def convert_to_fahrenheit(celsius):
#     return celsius * 9/5 + 32

# celsius_value = [0,20,37,100,-10]

# fahrenheit_value = map(convert_to_fahrenheit,celsius_value)

# print(list(fahrenheit_value))

def fahrenheit(celsius_value):
    return map(convert_to_fahrenheit, celsius_value)

def convert_to_fahrenheit(celsius):
    return (celsius * 9 / 5) + 32

celsius_value = [0, 20, 37, 100, -10]

print(list(fahrenheit(celsius_value)))






[32.0, 68.0, 98.6, 212.0, 14.0]
[32.0, 68.0, 98.6, 212.0, 14.0]


In [ ]:
#filter(function,iterable) return boolean value 

def is_even(x):
    return x%2 == 0

my_list = [1,2,3,4,5,6,7,8,9,10]

even_value = filter(is_even,my_list)

print(even_value)
print(list(even_value))

[2, 4, 6, 8, 10]


In [ ]:
#lambda function

add = lambda x,y : x+y
print(add(4,3))

7


In [ ]:
print((lambda x,y : x+y)(5,6))

11


In [ ]:
#given a list of integers, used map() with a lamda() to create a new list where each number id double

my_list = [1,2,3,4,5,6]

print(list((map(lambda number:number*2 , my_list))))

[2, 4, 6, 8, 10, 12]


In [ ]:
#you are given  the following list of integers 
#[12,18,17,15,22,23,16]
#write a python program that use the filter function with a lamda function to remore all odd numbers from the list

numbers = [12,18,17,15,22,23,16]

even_value = filter(lambda x :x % 2 == 0 , numbers )

print(list(even_value))

[12, 18, 22, 16]


In [ ]:
#write a python program with a lmbda function to decide the largest between two numbers 

max = lambda x,y : x if x >y else y

print(max(10,2))

10


In [ ]:
my_list = [4,5,6,1]

print(sum(my_list))
print(sum(my_list,10))

16
26


In [ ]:
#isinstance()   difine a class of object

x = 10
print(isinstance(x,int))

x = 10.5
print(isinstance(x,(int,float)))

True
True


In [ ]:
name = "kavindu"
age = 22

print(f"my name is {name} and my age is {age}")

my name is kavindu and my age is 22


In [ ]:
class Student:
    name = ""
    age = 0

    student_1 = Student()
    print(student_1.name)
    print(student_1.age)


0


In [ ]:
class Car:
    wheels = 4

    def display_info(self): #parameter ekk nthnm "self" danwa
        print(f"car has {self.wheels} wheels")

    def drive_to(self,location):
        print(f"car driving to {location} on {self.wheels} wheels")

car_1 = Car()
car_1.display_info()
car_1.drive_to("colombo")

car has 4 wheels
car driving to colombo on 4 wheels


In [ ]:
# Inheritance in python

class Animal:
    def speak(self):
        print("Animal Speaking")

class Parrot(Animal):  #Inheritance
    def display_info(self):
        print("somthing")

Parrot_1 = Parrot()
Parrot_1.speak()

Animal Speaking


In [ ]:
class Animal:
    def speak(self):
        print("Animal Speaking")

class Parrot(Animal):
    def speak(self):   #method overriding
        print("parrot speaking")

Parrot_1 = Parrot()
Parrot_1.speak()

Animal Speaking


In [ ]:
class Animal:
    def speak(self):
        print("Animal Speaking")

class Parrot(Animal):
    def speak(self,*name):   #method overloading
        print("parrot speaking",name)

Parrot_1 = Parrot()
Parrot_1.speak("age","kavindu")

# class Animal:
#     def speak(self):
#         print("Animal Speaking")

# class Parrot(Animal):
#     def speak(self, *args):  # accepts variable number of arguments
#         print("parrot speaking", args)

# Parrot_1 = Parrot()
# Parrot_1.speak("age", "kavindu")


parrot speaking ('age', 'kavindu')


In [ ]:
class Animal:
    def __init__(self,name):
        self.name = name

class Parrot(Animal):
    def speak(self):
        print("parrot speaking")

parrot_1 = Parrot("kavindu")
print(Parrot_1.name)

kavindu


In [ ]:
# class Animal:
#     def __init__(self,name):
#         self.name = name

# class Parrot(Animal):
#     def speak(self,name,color):
#         super().__init__(name)

#         self.color = color
        
#     def speak(self):
#         print("parrot speaking")

# parrot_1 = Parrot("kavindu","red")
# print(parrot_1.name)
# print(parrot_1.color)

class Animal:
    def __init__(self, name):
        self.name = name

class Parrot(Animal):
    def __init__(self, name, color):  # Constructor with 2 arguments
        super().__init__(name)        # Call Animal's constructor
        self.color = color

    def speak(self):
        print("parrot speaking")

parrot_1 = Parrot("kavindu", "red")
print(parrot_1.name)   # Output: kavindu
print(parrot_1.color)  # Output: red


kavindu
red


In [ ]:
#define a base class called employee that has attributes name and salary. it should have a method called display_info that prints the name and salary of the employee. then create a subclass called manager 
#that inherits from employee and adds an extra atributes called department. override the display_info method in the manager class to include the department information as well.final write a python program to
#1. create and object of the manager class
#2. call the display_info method using that object

class Employee:
    def __init__(self,name,sallary):
        self.name = name
        self.sallary = sallary

    def display_info(self):
        print("name :",self.name)
        print("sallary :",self.sallary)

class Manager(Employee):
    def __init__(self,name,sallary,department):
        super().__init__(name,sallary)
        self.department = department

    def display_info(self):
        super().display_info()
        print("department :",self.department)

manager = Manager("kavindu" , 100000 , "IT")
manager.display_info()
        



In [ ]:
#polymorphism in python

In [ ]:
#encapsulation

#public attributes
class Person:
    def __init__(self):
        self.name = "gamage"
        self.age = 28

class Employee(Person):
    def display(self):
        print(self.name)
        print(self.age)

employee = Employee()
print(employee.name)
print(employee.age)

#================================================================

#protected attributes
class Person:
    def __init__(self):
        self._name = "kavindu"

class Employee(Person):
    def display(self):
        print(self._name)

employee = Employee()
print(employee._name)

#================================================================

#private attributes
class Person:
    def __init__(self):
        self.__name = "tharaka"

    def get_name(self):
        return self.__name

person  = Person()  
print(person.get_name())

gamage
28
kavindu
tharaka


In [ ]:
#desine a python class called bank account that models a basic bank account using a consept of encapsulation 
# 1. use private attributes for acc_num , owner_name , balance(should start at 0.0 by default)
# 2. provide a constructer that accept only acc_num and owner_name the  balance should start at 0.0 inside the constructer
# 3. include the following public method 
#         *display account - prints the owners name and current balance (but not the account number)
#         *deposite(amount) - adds money to the account only if the amount is valid 
#         *withdraw(amount) - deducts money only if there is enough balance
#         *get_balance() - returns the current balance
#
# 4. implement a privet method call validate_amount (amount) that 
#         *returns true if the amount is a possitive number
#         *is used internally by both deposite() and withdraw() to validate input

class BankAccount:
    def __init__(self, acc_num, owner_name):
        self.__acc_num = acc_num
        self.__owner_name = owner_name
        self.__balance = 0.0

    def display_account(self):
        print(f"Owner Name: {self.__owner_name}")
        print(f"Balance: {self.__balance}")

    def validate_amount(self, amount):
        if amount > 0 :
            return True
        else:
            return False
    
    def deposite(self,amount):
        if self.validate_amount(amount):
            self.__balance += amount
        else:
            print("Invalid amount")

    def withdraw(self,amount):
        if self.validate_amount(amount):
            if self.__balance >= amount:
                self.__balance -= amount
            else:
                print("Insufficient balance")
        else:
            print("Invalid amount")

account = BankAccount("12345", "Kavindu")
account.display_account()
account.deposite(1000)
account.display_account()
account.deposite(1000)
account.display_account()
account.withdraw(500)
account.display_account()





Owner Name: Kavindu
Balance: 0.0
Owner Name: Kavindu
Balance: 1000.0
Owner Name: Kavindu
Balance: 2000.0
Owner Name: Kavindu
Balance: 1500.0


In [ ]:
#open a file
file_1 = open("my_file.txt")

#read a file
file_1 = open("my_file.txt", "r") 
read_content = file_1.read()
print(read_content)

#close a file
file_1.close


Hi Guys! Hope everthing is good. I'm fine too.
This is much better.
This is even better.
I love AI.


<function TextIOWrapper.close()>

In [ ]:
file_1 = open("my_file.txt")

line_1 = file_1.readline()
print(line_1)

line_2 = file_1.readline()
print(line_2)

file_1.close

Hi Guys! Hope everthing is good. I'm fine too.

This is much better.



<function TextIOWrapper.close()>

In [ ]:
file_1 = open("my_file.txt")

while True:
    line = file_1.readline()
    if not line:
        break
    print(line.strip())

file_1.close

Hi Guys! Hope everthing is good. I'm fine too.
This is much better.
This is even better.
I love AI.


<function TextIOWrapper.close()>

In [ ]:
file_1 = open("my_file.txt")

lines =  file_1.readlines()
print(lines)
print(type(lines))
print(lines[0])

for line in lines:
    print(line.strip())

file_1.close

["Hi Guys! Hope everthing is good. I'm fine too.\n", 'This is much better.\n', 'This is even better.\n', 'I love AI.']
<class 'list'>
Hi Guys! Hope everthing is good. I'm fine too.

Hi Guys! Hope everthing is good. I'm fine too.
This is much better.
This is even better.
I love AI.


<function TextIOWrapper.close()>

In [ ]:
with open ("my_file.txt","r") as file_1:
    lines = file_1.read()
    print(lines)


Hi Guys! Hope everthing is good. I'm fine too.
This is much better.
This is even better.
I love AI.


In [ ]:
with open("my_file_1.txt", "w") as file_1:
    file_1.write("Hello World.\n")
    file_1.write("Programming is fun.\n")

In [ ]:
with open("my_file_1.txt", "w") as file_1:
    file_1.write("My name is kavindu.\n")
    

In [ ]:
with open ("my_file.txt","w") as file_1:
    lines = ["this is new line\n", "this is another new line\n"]
    file_1.writelines(lines)

#append
with open ("my_file.txt","a") as file_1:
    file_1.write("this is append line")
    

In [ ]:
import json

with open("test.json", "r") as json_file:
    data = json.load(json_file)
    print(type(data))
    print(data)
    

<class 'dict'>
{'name': 'John Doe', 'age': 30, 'isStudent': False, 'hobbies': ['reading', 'gardening', 'swimming']}


In [ ]:
import json

data = {
    "name": "kavindu",
    "age": 22,
    "city": "galle"
}

with open("my_json.json", "w") as json_file:
    json.dump(data, json_file, indent=4)

In [ ]:
import csv

with open("test.csv", "r",newline="") as csv_file:
    csv_reader = csv.reader(csv_file)
    print(type(csv_reader))
    for row in csv_reader:
        print(row)

<class '_csv.reader'>
['Name', 'Age', 'Occupation']
['John Doe', '30', 'Engineer']
['Jane Smith', '25', 'Teacher']
['Bob Johnson', '40', 'Doctor']
['Alice Brown', '35', 'Artist']


In [ ]:
import csv

with open("test.csv", "r",newline="") as csv_file:
    csv_reader = csv.DictReader(csv_file)
    print(type(csv_reader))
    for row in csv_reader:
        print(row)

<class 'csv.DictReader'>
{'Name': 'John Doe', 'Age': '30', 'Occupation': 'Engineer'}
{'Name': 'Jane Smith', 'Age': '25', 'Occupation': 'Teacher'}
{'Name': 'Bob Johnson', 'Age': '40', 'Occupation': 'Doctor'}
{'Name': 'Alice Brown', 'Age': '35', 'Occupation': 'Artist'}


In [ ]:
import csv

data = [
    {"name": "kavindu", "age": 22, "city": "galle"},
    {"name": "tharaka", "age": 18, "city": "matara"},
    {"name": "gamagae", "age": 28, "city": "colombo"},
]

with open("test.csv", "w",newline="") as csv_file:
    fieldnames = ["name", "age", "city"]
    csv_writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
    
    csv_writer.writeheader()
    csv_writer.writerows(data)


In [ ]:
#pip install numpy
#numpy arrays

import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
arr_1 = np.array([1,2,3])
arr_2 = np.array([1,2,3])

result_addition =  arr_1 + arr_2
result_2 = arr_1 - arr_2
result_3 = arr_1 * arr_2
result_4 = arr_1 / arr_2

print(result_addition)
print(result_2)
print(result_3)
print(result_4)             

[2 4 6]
[0 0 0]
[1 4 9]
[1. 1. 1.]


In [ ]:
arr_1 = np.array([30,16,14,22])

print(np.sqrt(arr_1))
print(np.sum(arr_1))
   

[5.47722558 4.         3.74165739 4.69041576]
82
19.0
6.224949798994366


In [ ]:
#maximum and minimum value

arr_1 = np.array([50,70,20,65])

result_1 = np.max(arr_1)
result_2 = np.min(arr_1)

print(result_1)
print(result_2)

70
20


In [ ]:
#multidimensional arrays 
#2D arrays
arr_1 = np.array([[1,2,3],[4,5,6]])
print(arr_1)

print(arr_1.size)
print(arr_1.ndim)
print(arr_1.shape)

[[1 2 3]
 [4 5 6]]
6
2
(2, 3)


In [ ]:
#3D arrays
arr_2 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr_2)

print(arr_2.size)
print(arr_2.ndim)
print(arr_2.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
12
3
(2, 2, 3)


In [ ]:
#dtype
arr_1 = np.array([1,2,3,4,5])
print(arr_1)
print(arr_1.dtype)

[1 2 3 1 5]
int64


In [ ]:
#arry indexing 
arr_1 = np.array([1,2,3,4,5])
print(arr_1[0])  # Accessing the first element
print(arr_1[-1])  # Accessing the last element
print(arr_1[1:4])  # Accessing elements from index 1 to 3 (not including 4)
print(arr_1[::-1])  # Reversing the array

#arry indexing in 2D arrays
arr_2 = np.array([[1,2,3],[4,5,6]])
print(arr_2[1,2])  # Accessing the element at row 0, column 1
print(arr_2[1, :])  # Accessing the entire second row
print(arr_2[:, 2])  # Accessing the third column    
print(arr_2[-2, -2])


1
5
[2 3 4]
[5 4 3 2 1]
6
[4 5 6]
[3 6]
2


In [ ]:
#boolean indexing
arr_1 = np.array([30,10,40,50,20])

condition = arr_1 > 25

print(condition)
print(arr_1[condition])  # Accessing elements that satisfy the condition
print(arr_1[arr_1 > 25])  # Another way to access elements that satisfy the condition
print(arr_1[(arr_1 > 25) & (arr_1 < 45) ])  


[ True False  True  True False]
[30 40 50]
[30 40 50]
[30 40]


In [ ]:
#you are given the following array representing in body tempresure (celsius) of five patients or three times (moening,afternoon,evening)
# 31  30  28
# 29  29  32
# 26  24  27
# 31  34  35
# 28  31  30  readings of the patients body temprsure
#identify and extract all tempresure readings grater than the daily average temprsure using boolean  indexing


tempresure = np.array([[31,30,28],[29,29,32],[26,24,27],[31,34,35],[28,31,30]])

daily_average = np.mean(tempresure)

print(daily_average)

print(tempresure[tempresure > daily_average])

29.666666666666668
[31 30 32 31 34 35 31 30]


In [ ]:
#numpy.zeros
# np.zeros(shape , dtype=float)

print(np.zeros((2,3)))  # 2D array with shape (2,3) filled with zeros

print(np.zeros(5)) # 1D array with 5 elements filled with zeros

[[0. 0. 0.]
 [0. 0. 0.]]
[0. 0. 0. 0. 0.]


In [ ]:
print(np.full((2,3), 7))
print(np.full((2,3), (1, 2, 3)))  

[[7 7 7]
 [7 7 7]]
[[1 2 3]
 [1 2 3]]


In [ ]:
#numpy.empty
print(np.empty((2,3)))  # 2D array with shape (2,3) filled with uninitialized values

[[4.9e-324 9.9e-324 1.5e-323]
 [4.9e-324 9.9e-324 1.5e-323]]


In [ ]:
#Pandas library

import pandas as pd

data = {"Name" : ["Alice", "Bob", "Charlie", "David"],
        "Age" : [25, 30, 35,23],}

df = pd.DataFrame(data)
print(df)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   23


In [ ]:
#loc command
print(df.loc[0,'Name']) # Accessing the first row and 'Name' column

#iloc command
print(df.iloc[2, 1])  # Accessing the first row and first column

Alice
35


In [ ]:
#how to get rows by row name
print(df.loc[2])  # Accessing the row with index 2

print(df.iloc[2])  



Name    Charlie
Age          35
Name: 2, dtype: object
Name    Charlie
Age          35
Name: 2, dtype: object


In [ ]:
df = pd.DataFrame(data,index=["kavindu", "tharaka", "gamage", "saman"])
print(df)

print(df.iloc[1])  

print(df.loc["gamage"])  

print(df.loc[["kavindu", "saman"]])



            Name  Age
kavindu    Alice   25
tharaka      Bob   30
gamage   Charlie   35
saman      David   23
Name    Bob
Age      30
Name: tharaka, dtype: object
Name    Charlie
Age          35
Name: gamage, dtype: object
          Name  Age
kavindu  Alice   25
saman    David   23


In [ ]:
age_column = df["Age"]
print(age_column)

print(df.columns)  # Accessing all column names
print(list(df.columns))  # Converting column names to a list


kavindu    25
tharaka    30
gamage     35
saman      23
Name: Age, dtype: int64
Index(['Name', 'Age'], dtype='object')
['Name', 'Age']


In [ ]:
print(df.size)  # Getting the number of elements in the DataFrame
print(df.shape)  # Getting the shape of the DataFrame (rows, columns)
print(len(df))  

print(df.values)  # Getting the values of the DataFrame as a NumPy array
print(type(df.values))  # Checking the type of the values

8
(4, 2)
4
[['Alice' 25]
 ['Bob' 30]
 ['Charlie' 35]
 ['David' 23]]
<class 'numpy.ndarray'>


In [ ]:
#DataFrame.mean()

print(df['Age'].mean())
print(df['Age'].sum())  

28.25
113


In [ ]:
df['city'] = ["colombo", "galle", "matara", "kandy"]

df['salary'] = [50000, 60000, 70000, 80000]
print(df)

            Name  Age     city  salary
kavindu    Alice   25  colombo   50000
tharaka      Bob   30    galle   60000
gamage   Charlie   35   matara   70000
saman      David   23    kandy   80000


In [ ]:
#Filtering rows in a DataFrame
print(df[df['Age'] > 30])  # Filtering rows where 'Age' is

           Name  Age    city  salary
gamage  Charlie   35  matara   70000


In [ ]:
print(df[(df['Age'] > 28) & (df['salary'] < 65000)])  

        Name  Age   city  salary
tharaka  Bob   30  galle   60000


In [ ]:
#you are given the following data set representing the exam records of students in a programming course the data includes marks for two assignment and the final exam 
#
# s_id    name    ass_1  ass_2  fin_ex
# 1001   ayesha     78     85     90
# 1002   nimal      65     70     72
# 1003   tharindu   88     90     95
# 1004   kasun      50     45     60
# 1005   shashini   80     75     85

#write a python progarm using pandas to,
# 1.create a data frame using the data given about
# 2.display the name of all student who score more than 80 in the final exam
# 3.computer average scope each students across all three assesments and add it as a new column call "Average"
# 4.display the student(s) with the highest average score
# 5.calculate and display the total marks scored by all students in assignment_1

#Q 01
student_data = {
    "student_id" : [1001,1002,1003,1004,1005],
    "name" : ["ayesha","nimal","tharindu","kasun","shashini"],
    "assignment_1" : [78,65,88,50,80],
    "assignment_2" : [85,70,90,45,75],
    "final_exam" : [90,72,95,60,85]
}

s_df = pd.DataFrame(student_data)
print(s_df)
print()
print("====================================================================================")

#Q 02
# print(s_df[s_df["final_exam"] > 80]["name"])

high_marks = s_df[s_df["final_exam"] > 80]
print(high_marks[["name" , "final_exam"]])
print()
print("====================================================================================")

#Q 03
s_df["Average"] = (s_df["assignment_1"] + s_df["assignment_2"] + s_df["final_exam"]) / 3
print(s_df)
print()
print("====================================================================================")

#Q 04
print(s_df[s_df["Average"] == s_df["Average"].max()][["name", "Average"]])
print()

print("====================================================================================")

#Q 05
print(s_df['assignment_1'].sum()) 




   student_id      name  assignment_1  assignment_2  final_exam
0        1001    ayesha            78            85          90
1        1002     nimal            65            70          72
2        1003  tharindu            88            90          95
3        1004     kasun            50            45          60
4        1005  shashini            80            75          85

       name  final_exam
0    ayesha          90
2  tharindu          95
4  shashini          85

   student_id      name  assignment_1  assignment_2  final_exam    Average
0        1001    ayesha            78            85          90  84.333333
1        1002     nimal            65            70          72  69.000000
2        1003  tharindu            88            90          95  91.000000
3        1004     kasun            50            45          60  51.666667
4        1005  shashini            80            75          85  80.000000

       name  Average
2  tharindu     91.0

361


In [ ]:
df = pd.read_csv("test.csv")
print(df)
print(type(df))  # Checking the type of the DataFrame (df)

      name  age     city
0  kavindu   22    galle
1  tharaka   18   matara
2  gamagae   28  colombo
<class 'pandas.core.frame.DataFrame'>


In [ ]:
import requests

response = requests.get("https://api.github.com/events")

print(response) #output: <Response [200]>
print(type(response))  # Checking the type of the response object
print(response.status_code)  # Checking the status code of the response

<Response [200]>
<class 'requests.models.Response'>
200


In [ ]:
import requests

response = requests.get("https://api.github.com/events")

if response.status_code == 200:
    print("Success!")
    print(response.url)  # Printing the URL of the response
    print(response.headers) 
    print(type(response.headers))

    print(response.headers['Content-Type']) 

    print(response.text)

else:
    print("Error:", response.status_code)



Success!
https://api.github.com/events
{'Date': 'Wed, 23 Jul 2025 04:00:19 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'public, max-age=60, s-maxage=60', 'Vary': 'Accept,Accept-Encoding, Accept, X-Requested-With', 'ETag': 'W/"4cd1f8d6c2f359465ea181a3bee0402bd7c5a97366bc022352d6876aa1a5b071"', 'Last-Modified': 'Wed, 23 Jul 2025 03:55:19 GMT', 'X-Poll-Interval': '60', 'X-GitHub-Media-Type': 'github.v3; format=json', 'Link': '<https://api.github.com/events?page=2>; rel="next", <https://api.github.com/events?page=10>; rel="last"', 'x-github-api-version-selected': '2022-11-28', 'Access-Control-Expose-Headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset', 'Access-Control-Allow-Origin': '*', 'Strict-Transport-Security': 'max-

In [ ]:
import json

response = requests.get("https://api.github.com/events")

data = response.json()  # Parsing the JSON response

print(data)
print(type(data))  # Checking the type of the parsed data

[{'id': '52424042159', 'type': 'PushEvent', 'actor': {'id': 18281711, 'login': 'ahmadtara', 'display_login': 'ahmadtara', 'gravatar_id': '', 'url': 'https://api.github.com/users/ahmadtara', 'avatar_url': 'https://avatars.githubusercontent.com/u/18281711?'}, 'repo': {'id': 1024244835, 'name': 'ahmadtara/testingtara', 'url': 'https://api.github.com/repos/ahmadtara/testingtara'}, 'payload': {'repository_id': 1024244835, 'push_id': 25665820710, 'size': 1, 'distinct_size': 1, 'ref': 'refs/heads/main', 'head': '776bff62f05b4ced0ef2bf7870d08e9ee2f22c15', 'before': '2fc614cce77556fad45db1242cf3589fc2e9faed', 'commits': [{'sha': '776bff62f05b4ced0ef2bf7870d08e9ee2f22c15', 'author': {'email': 'ahmadtara.pratama@gmail.com', 'name': 'ahmadtara'}, 'message': 'Update requirements.txt', 'distinct': True, 'url': 'https://api.github.com/repos/ahmadtara/testingtara/commits/776bff62f05b4ced0ef2bf7870d08e9ee2f22c15'}]}, 'public': True, 'created_at': '2025-07-23T04:03:45Z'}, {'id': '52424042166', 'type': '

In [ ]:
import requests
import json

response = requests.get("https://api.github.com/events")

if response.status_code == 200:
    print("Success!") 
    print(response.url)  

    if 'application/json' in response.headers.get('Content-Type'):
        data = response.json()
        print(data)

        print(response.text)

    else:
        print("Response is not in JSON format",response.status_code)

else:
    print("Error:", response.status_code)    

Success!
https://api.github.com/events
[{'id': '52424705317', 'type': 'PushEvent', 'actor': {'id': 38610494, 'login': 'kaiyuanzhuadmin', 'display_login': 'kaiyuanzhuadmin', 'gravatar_id': '', 'url': 'https://api.github.com/users/kaiyuanzhuadmin', 'avatar_url': 'https://avatars.githubusercontent.com/u/38610494?'}, 'repo': {'id': 1014600798, 'name': 'kaiyuanzhuadmin/cat', 'url': 'https://api.github.com/repos/kaiyuanzhuadmin/cat'}, 'payload': {'repository_id': 1014600798, 'push_id': 25666155974, 'size': 1, 'distinct_size': 1, 'ref': 'refs/heads/main', 'head': 'b04ec285cdc90155fb0e3e7baa00c83a496503df', 'before': 'b98fc6f2e6744fb1a1b08e1f6bf29b510a7cb5c9', 'commits': [{'sha': 'b04ec285cdc90155fb0e3e7baa00c83a496503df', 'author': {'email': '38610494+kaiyuanzhuadmin@users.noreply.github.com', 'name': 'kaiyuanzhuadmin'}, 'message': '更新 index.html', 'distinct': True, 'url': 'https://api.github.com/repos/kaiyuanzhuadmin/cat/commits/b04ec285cdc90155fb0e3e7baa00c83a496503df'}]}, 'public': True, '

In [ ]:
import requests

url = "https://httpbin.org/post"
data = { 'username': 'user', 'password': 'pass' }
response = requests.post(url, data=data)

if response.status_code == 200:
    print("Login Success!")
    print(response.url)
    print(response.text)
else:
    print("Error:", response.status_code)

Login Success!
https://httpbin.org/post
{
  "args": {}, 
  "data": "", 
  "files": {}, 
  "form": {
    "password": "pass", 
    "username": "user"
  }, 
  "headers": {
    "Accept": "*/*", 
    "Accept-Encoding": "gzip, deflate", 
    "Content-Length": "27", 
    "Content-Type": "application/x-www-form-urlencoded", 
    "Host": "httpbin.org", 
    "User-Agent": "python-requests/2.32.4", 
    "X-Amzn-Trace-Id": "Root=1-68806a66-2ec38e6773fa7dc4347731f6"
  }, 
  "json": null, 
  "origin": "175.157.241.106", 
  "url": "https://httpbin.org/post"
}



In [ ]:
#url parameters

import requests

url = "http://jsonplaceholder.typicode.com/posts"
params = {'userId': 1, 'id': 2}
response = requests.get(url, params=params)

print(response.url)  # Printing the URL with parameters
print(response.status_code)  # Checking the status code of the response 
print(response.text)

http://jsonplaceholder.typicode.com/posts?userId=1&id=2
200
[
  {
    "userId": 1,
    "id": 2,
    "title": "qui est esse",
    "body": "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla"
  }
]


In [ ]:
import requests

url = 'http://httpbin.org/get'

username = 'kavindu'
password = '1234'

response = requests.get(url, auth=(username, password))

if response.status_code == 200:
    print("Authentication Success!")
    print(response.text)
else:
    print("Authentication Failed:", response.status_code)

Authentication Success!
{
  "args": {}, 
  "headers": {
    "Accept": "*/*", 
    "Accept-Encoding": "gzip, deflate", 
    "Authorization": "Basic a2F2aW5kdToxMjM0", 
    "Host": "httpbin.org", 
    "User-Agent": "python-requests/2.32.4", 
    "X-Amzn-Trace-Id": "Root=1-68807141-65ec8dc264c967037d52380d"
  }, 
  "origin": "175.157.241.106", 
  "url": "http://httpbin.org/get"
}



In [ ]:
from bs4 import BeautifulSoup

html_doc = """<html><head><title>The Dormouse's story</title></head>
<body>
<p class="title"><b>The Dormouse's story</b></p>
<p class="story">Once upon a time there were three little sisters; and their names were
<a href="http://example.com/elsie&quot; class="sister" id="link1">Elsie</a>,
<a href="http://example.com/lacie&quot; class="sister" id="link2">Lacie</a> and
<a href="http://example.com/tillie&quot; class="sister" id="link3">Tillie</a>;
and they lived at the bottom of a well.</p>
<p class="story">...</p>
</body>
</html>"""

soup = BeautifulSoup(html_doc, 'html.parser')

print(soup.title)
print(soup.p)
print(soup.a)
print()

P_tag = soup.find('p')
print(P_tag)  # Printing the first <p> tag found in the HTML document
print()

P_tags = soup.find_all('p')
print(P_tags)  # Printing all <p> tags found in the HTML document

<title>The Dormouse's story</title>
<p class="title"><b>The Dormouse's story</b></p>
<a href='http://example.com/elsie" class=' id="link1" sister"="">Elsie</a>

<p class="title"><b>The Dormouse's story</b></p>

[<p class="title"><b>The Dormouse's story</b></p>, <p class="story">Once upon a time there were three little sisters; and their names were
<a href='http://example.com/elsie" class=' id="link1" sister"="">Elsie</a>,
<a href='http://example.com/lacie" class=' id="link2" sister"="">Lacie</a> and
<a href='http://example.com/tillie" class=' id="link3" sister"="">Tillie</a>;
and they lived at the bottom of a well.</p>, <p class="story">...</p>]


In [ ]:
# fetch the web page ,check if the request was successful,and extract the main heading text from the page's content.you can assume that the base url is'http://example.com'

import  requests
from bs4 import BeautifulSoup

url = "http://example.com"
response = requests.get(url)

if response.status_code == 200:
    print("Request was successful!")
    
    soup = BeautifulSoup(response.text, 'html.parser')
    main_heading = soup.find('h1') 

    if main_heading:
        print("Main Heading:", main_heading.text)

    else:
        print("main heading not found")
else:
    print("Request failed with status code:", response.status_code)


Request was successful!
Main Heading: Example Domain


In [ ]:
#API Integration

import requests

url = "https://api.open-meteo.com/v1/forecast?"

params = {
    "latitude": 52.52,
    "longitude": 13.41,
    "current_weather": "true",
}

response = requests.get(url, params)

if response.status_code == 200:
    data = response.json()
    current_weather = data["current_weather"]
    
    temperature = current_weather["temperature"]
    windspeed = current_weather["windspeed"]

    print(f"Temperature: {temperature}°C")
    print(f"Windspeed: {windspeed} km/h")
    print(current_weather)


Temperature: 18.1°C
Windspeed: 18.9 km/h
{'time': '2025-07-23T09:15', 'interval': 900, 'temperature': 18.1, 'windspeed': 18.9, 'winddirection': 235, 'is_day': 1, 'weathercode': 61}


In [ ]:
import requests

def fetch_weather(latitude, longitude,current_weather):

    url = "https://api.open-meteo.com/v1/forecast?"
    params = {
        "latitude": latitude,
        "longitude": longitude,
        "current_weather": current_weather
    }
        
    if response.status_code == 200:
        return response.json()
    else:
        print("Error fetching weather data:", response.status_code)
        return None
    3.
def parsing_weather_data(weather_data):
    if weather_data:
     temperature = weather_data["current_weather"]["temperature"]
     windspeed = weather_data["current_weather"]["windspeed"]
     
     print(temperature)
     print(windspeed)

    else:
       return None   
     
weather_data =  fetch_weather(52.52, 13.41,"temperature_2m,wind_speed_10m")       
parsing_weather_data(weather_data)



18.1
18.9


In [1]:
#Debugging Functions

# 1.Syntax error
# 2.Runtime error
# 3.Logical error
